### ISSUE TITLE
.JAR

### ISSUE THREAD

**Issue by yourrree** [3arthqu4ke/PingBypassClient#7]
Ok a response to 3arthqu4ke, I've try download another .JAR already unencrypted. I cant seem to get anything binded besides crystal aura, no clickgui. I mainly need help with the unencrypt part.

**Comment by 3arthqu4ke** [comment]
I have no clue what you are talking about. There's nothing to encrypt. There's no ClickGui, you need to use commands.

**Comment by yourrree** [comment]
Such as? I can only seem to get autocrystal and it doesn't work. About the encrypt part I mean making it a .jar file. @3arthqu4ke

**Comment by yourrree** [comment]
@3arthqu4ke

**Comment by 3arthqu4ke** [comment]
Use +modules to get a list of modules. Use +<modulename> to do stuff with modules.

**Comment by yourrree** [comment]
My ca doesnt work. @3arthqu4ke

**Comment by 3arthqu4ke** [comment]
Do you understand what PingBypass is? You need to connect to a PingBypass Proxy for it to work.

**Comment by yourrree** [comment]
So. I need to build the PingBypass and I'm having trouble doing it. I
don't have the gradlew text file because I don't know how to make one.

**Comment by 3arthqu4ke** [comment]
You don't need to make a "gradlew text file"?
Read forges [documentation ](https://mcforge.readthedocs.io/en/latest/) or watch a Youtube Tutorial...
