### ISSUE TITLE
it wont stop shouting off my settings

### ISSUE THREAD

**Issue by Albertgud** [3arthqu4ke/PingBypassClient#9]
![4da31ca12e7c414302d5818ac02159bc](https://user-images.githubusercontent.com/90953107/134388465-a714072a-7de3-46fb-b832-92af86da2f91.png)
idk what to do

**Comment by 3arthqu4ke** [comment]
Just turn it off when you join a Singleplayer world. It doesn't do this on acutal servers, right?
